### PR TITLE
update prelude

### PR DESCRIPTION
**Pull request by c-cube**
crossing fingers for the BS part :worried:

### CODE REVIEW

**Comment by actionshrimp** [comment]
hmm, BS is still on ocaml 4.06 so not entirely sure if the directly extacted version will work 🤔

**Comment by c-cube** [comment]
oh I tried to update by hand, but maybe the let operators need to be entirely removed?

**Comment by actionshrimp** [comment]
yeah that'll probably do it - ill give it a go locally

**Comment by actionshrimp** [comment]
hmm it's a bit happier now - did some stuff change with `Prelude` vs `Stdlib` in 4.08 too? we have a bunch of refs to Stdlib which the BS compiler doesnt like either :-(

**Comment by c-cube** [comment]
hmm the Imandra prelude now uses `Stdlib` everywhere, since `Pervasives` is deprecated in 4.08. I suppose BS still needs `Pervasives`, so maybe starting with `module Stdlib = Pervasives` at the top would help?

**Comment by actionshrimp** [comment]
This all seems to work locally for BS now - the travis build failures are for the normal ocaml version AFAICT

**Review by actionshrimp — APPROVED** [review]

**Comment by c-cube** [comment]
ready for merge then?

**Pull request merged**
